version: "3"

services:
  server:
    platform: linux/amd64
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
