version: "3"

services:
  server:
    platform: linux/amd64
    build:
      context: ./server
      dockerfile: ./Dockerfile.demoserver
    ports:
      - "5000:5000"
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile.democlient
    ports:
      - "3000:3000"
